development:
  adapter: postgresql
  database: anaconda_dev
  encoding: unicode
  # Create this user in your local PostgreSQL database.
  # Example: CREATE USER anaconda_dev WITH CREATEDB NOCREATEUSER;
  username: anaconda_dev

test:
  adapter: postgresql
  database: anaconda_tst
  encoding: unicode
  # Create this user in your local PostgreSQL database.
  # Example: CREATE USER anaconda_tst WITH CREATEDB NOCREATEUSER;
  username: anaconda_tst
